### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by joshuabaker** [jamiepittock/craft-essence#1]
Have you seen [joshuabaker/craft-essence](https://github.com/joshuabaker/craft-essence)?

**Comment by jamiepittock** [comment]
Yeah I have https://twitter.com/jamiepittock/status/534805104336306176

**Comment by joshuabaker** [comment]
Missed that! Feel free to contribute ideas or code. Always happy to share credit. :wink:

**Comment by jamiepittock** [comment]
Will do. We ended up carrying on using ours simply because it worked and at the time we had bigger fish to fry! Yours does still look like the better foundation though so it's still on the list to switch at some point and retire ours.

**Comment by Potherca** [comment]
@jamiepittock You might want to put that in the `README` instead of

> Full docs coming soon.

:smirk_cat:
